version: "3"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:3.6
    ports:
      - 27017:27017
  app:
    container_name: node-app
    restart: always
    build: .
    ports:
      - 80:3000
    external_links:
      - mongo
